apiVersion: v1
kind: Service
metadata:
  name: member-svc
  labels:
    component: member-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: default-port
  selector:
    component: member-api-pod