apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-api-deploy-pod
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        component: user-api-pod
    spec:
      containers:
        - name: api-con
          image: 123.dkr.ecr.ap-southeast-2.amazonaws.com/user:prod
          livenessProbe:
              httpGet:
                path: /health/alive
                port: 80
          readinessProbe: 
              httpGet:
                path: /health/ready
                port: 80
          env:
            - name: DB_HOST
              value: 
            - name: DB_PORT
              value: 
            - name: DB_DATABASE
              value: 
            - name: DB_USERNAME
              value: 
            - name: DB_PASSWORD
              value: 
          ports:
            - containerPort: 80
              name: api-port
